[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  flush_interval = "10s"

[[inputs.mqtt_consumer]]
  servers = ["tcp://emqx:1883"]
  topics = ["#"]
  username = "${EMQX_TELEGRAF_USER}"
  password = "${EMQX_TELEGRAF_PASSWORD}"
  client_id = "telegraf-subscriber"
  data_format = "json"
  topic_tag = "topic"
  qos = 1

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "${INFLUXDB_ADMIN_TOKEN}"
  organization = "${INFLUXDB_ORG}"
  bucket = "${INFLUXDB_BUCKET}"
